package spicefyne

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/driver/desktop"
)

// fyne → AT scancode table
// see: http://www.philipstorr.id.au/pcbook/book3/scancode.htm
var fyneScancodeMap = map[fyne.KeyName][]byte{
	fyne.KeyEscape:    []byte{0x01},
	fyne.KeyTab:       []byte{0x0f},
	fyne.KeyBackspace: []byte{0x0e},
	fyne.KeyInsert:    []byte{0xe0, 0x52},
	fyne.KeyDelete:    []byte{0xe0, 0x53},
	fyne.KeyRight:     []byte{0xe0, 0x4d},
	fyne.KeyLeft:      []byte{0xe0, 0x4b},
	fyne.KeyDown:      []byte{0xe0, 0x50},
	fyne.KeyUp:        []byte{0xe0, 0x48},
	fyne.KeyPageUp:    []byte{0xe0, 0x49},
	fyne.KeyPageDown:  []byte{0xe0, 0x51},
	fyne.KeyHome:      []byte{0xe0, 0x47},
	fyne.KeyEnd:       []byte{0xe0, 0x4f},

	fyne.KeyF1:  []byte{0x3b},
	fyne.KeyF2:  []byte{0x3c},
	fyne.KeyF3:  []byte{0x3d},
	fyne.KeyF4:  []byte{0x3e},
	fyne.KeyF5:  []byte{0x3f},
	fyne.KeyF6:  []byte{0x40},
	fyne.KeyF7:  []byte{0x41},
	fyne.KeyF8:  []byte{0x42},
	fyne.KeyF9:  []byte{0x43},
	fyne.KeyF10: []byte{0x44},
	fyne.KeyF11: []byte{0x57},
	fyne.KeyF12: []byte{0x58},

	fyne.Key1: []byte{0x02},
	fyne.Key2: []byte{0x03},
	fyne.Key3: []byte{0x04},
	fyne.Key4: []byte{0x05},
	fyne.Key5: []byte{0x06},
	fyne.Key6: []byte{0x07},
	fyne.Key7: []byte{0x08},
	fyne.Key8: []byte{0x09},
	fyne.Key9: []byte{0x0a},
	fyne.Key0: []byte{0x0b},

	fyne.KeyA: []byte{0x1e},
	fyne.KeyB: []byte{0x30},
	fyne.KeyC: []byte{0x2e},
	fyne.KeyD: []byte{0x20},
	fyne.KeyE: []byte{0x12},
	fyne.KeyF: []byte{0x21},
	fyne.KeyG: []byte{0x22},
	fyne.KeyH: []byte{0x23},
	fyne.KeyI: []byte{0x17},
	fyne.KeyJ: []byte{0x24},
	fyne.KeyK: []byte{0x25},
	fyne.KeyL: []byte{0x26},
	fyne.KeyM: []byte{0x32},
	fyne.KeyN: []byte{0x31},
	fyne.KeyO: []byte{0x18},
	fyne.KeyP: []byte{0x19},
	fyne.KeyQ: []byte{0x10},
	fyne.KeyR: []byte{0x13},
	fyne.KeyS: []byte{0x1f},
	fyne.KeyT: []byte{0x14},
	fyne.KeyU: []byte{0x16},
	fyne.KeyV: []byte{0x2f},
	fyne.KeyW: []byte{0x11},
	fyne.KeyX: []byte{0x2d},
	fyne.KeyY: []byte{0x15},
	fyne.KeyZ: []byte{0x2c},

	fyne.KeySpace:        []byte{0x39},
	fyne.KeyApostrophe:   []byte{0x28}, // Quote
	fyne.KeyComma:        []byte{0x33},
	fyne.KeyMinus:        []byte{0x0c},
	fyne.KeyPeriod:       []byte{0x34},
	fyne.KeySlash:        []byte{0x35},
	fyne.KeyBackslash:    []byte{0x2b},
	fyne.KeyLeftBracket:  []byte{0x1a},
	fyne.KeyRightBracket: []byte{0x1b},
	fyne.KeySemicolon:    []byte{0x27},
	fyne.KeyEqual:        []byte{0x0d},
	fyne.KeyAsterisk:     []byte{0x37},
	fyne.KeyPlus:         []byte{0x4e},
	fyne.KeyBackTick:     []byte{0x29}, // Backquote

	fyne.KeyReturn:          []byte{0xe0, 0x1c},
	fyne.KeyEnter:           []byte{0x1c},
	desktop.KeyShiftLeft:    []byte{0x2a},
	desktop.KeyShiftRight:   []byte{0x36},
	desktop.KeyControlLeft:  []byte{0x1d},
	desktop.KeyControlRight: []byte{0xe0, 0x1d},
	desktop.KeyAltLeft:      []byte{0x38},
	desktop.KeyAltRight:     []byte{0xe0, 0x38},
	desktop.KeyCapsLock:     []byte{0x3a},
	desktop.KeyMenu:         []byte{0xe0, 0x5d},
	desktop.KeyPrintScreen:  []byte{0xe0, 0x2a, 0xe0, 0x37},

	desktop.KeySuperLeft:  []byte{0xe0, 0x5b},
	desktop.KeySuperRight: []byte{0xe0, 0x5c},
}
